welcome: |
  <b>Что умеет этот бот?</b>
  Привет! Тут вы найдете все самое современное и
  эффективное, что бы справится с избыточным весом и
  улучшить свое здоровье!
  Мы Мирон и Оксана Шакира создали этот ресурс для вас и
  будем поддерживать вас на каждом шаге. Хорошего
  путешествия к стройности и здоровью! Это проще чем вам
  кажется!
  Нажимайте старт и вперед!
start_button: Старт
welcome_after_start: |
  Привет Я ШакираFIT бот. Я помогу вам стать стройным и
  здоровым человеком на основании самых современных и
  научных данных. Вы сможете помочь не только себе но и
  вашим близким.
  Выберете курс который вас заинтересовал. Все курсы
  созданы для того, что бы вы за максимальное короткое
  время смогли получить самые важные знания и очень
  хорошо усвоить их.
select_course: |
  Выберите подходящий курс из списка
course_name_format: "{0} {1}"  # {0} Will be replaced with course name, and {1} with display price (Or checkmark if already bought)

buy_course_text: |
  Выберите способ оплаты
buy_course_button: Оплата курса
buy_course_russia_button: Оплата курса из России
invoice_created_text: |
  Инвойс создан. После оплаты, нажмите кнопку "Проверить оплату", чтобы получить курс
  <b>Обработка может занять некоторое время!</b>
check_invoice_button: Проверить оплату
expired_invoice: |
  Этот инвойс истёк. Кажется, вы не успели его оплатить! 
  Попробуйте создать новый
created_invoice: |
  Оплата пока не произведена. Обработка может занять некоторое время
unknown_invoice: |
  Инвойс не найден.
  Возможно, вы уже его оплатили?
success_invoice: |
  Спасибо за оплату!
  Курс был добавлен на ваш аккаунт!
start_course_button: Начать курс
select_block: Выберите блок курса
back_button: Назад